name: dbt_dvf
version: '1.0.0'
config-version: 2

profile: dbt_dvf

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_dvf:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
